160815
多个catch语句
异常范围由小到大


Exception in thread "main" java.lang.RuntimeException: From f()  异常发生地方
	at exceptions.NeverCaught.f(NeverCaught.java:11)  异常发生地方
	at exceptions.NeverCaught.g(NeverCaught.java:16)
	at exceptions.NeverCaught.main(NeverCaught.java:21) 调用地方

二.异常 发生 尝试次数
方法1:将try放入循环中
方法2:用一个static类型的计数器,在异常发生时尝试一定次数

三.异常信息丢失
1.在前一个异常还未处理时就抛出下一个异常,会导致前一个异常信息丢失
2.在finally中返回,会导致异常信息丢失

四.构造器可抛出任何异常,而与父类构造器无关